(newline)
(display "*****")
(display "Number Data Type")
(newline)
(display (integer? 9)) (newline)
(display (rational? 9))(newline)
(display (rational? 9.))(newline)
(display (rational? 9.1))(newline)
(display (rational? (/ 8 3)))(newline)
(display (rational? 8/3))(newline)
(display (real? 9))(newline)
(display (complex? 9))(newline)
(display (number? 9))(newline)
(display (rational? (sqrt 4)))(newline)
(display (rational? (sqrt 4.)))(newline)
(display (sqrt 2))(newline)
(display (rational? (sqrt 2.)))(newline)
(display (rational? 1.4142135623730951))(newline)
(display (rational? 1.1111111111111111))(newline)
;(pause)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
;(pause)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(display (sqrt 9))
(newline)
(display (sqrt 3))
(newline)
(display (sqrt -1))
(newline)

(display (/ 64. 8))
(newline)
(display (/ 64 8))
(newline)
(display (/ 64 7))
; justify 1
(newline)
(display (/ 64 7.))
;(pause)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(display (* 4 3 2))
(newline)
(display (- 4 3 2))
(newline)
(display (+ 4 3 2))
(newline)
(display (/ 4 3 2))
(newline)
(display (/ 9))
(newline)
(display (/ 5 4 3 2))
(newline)
;(pause)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
(newline)
;(pause)
(display (expt 2 3))
(newline)
(display (expt 2 -3))
(newline)
;(display (expt 2 3 2))
(newline)
;(pause)
(newline)
(display (max 1 -1 1 9 9.))
;justify 
(newline)
(display (min 1 3 7 1.))
;justify 
(newline)
(display (- 9 9.))
(newline)
(display (- 9. 9))
(newline)
;justify 
(display (abs (- (/ 4))))
(newline)
(newline)
;jhklk1
(display (eqv? 33 33))
(newline)
;2
(display (eqv? #t #t))
(newline)
;3
(display (eqv? 33 #t))
(newline)
;4
(display (eqv? false #f))
(newline)
;5
(display (eqv? 33 33.))
(newline)
;6
(display (= 33 33.))
(newline)
;7
;(display (= 33 #t))
(newline)
(display "******")
;(pause)
;(display (char? #\))
;(newline)
;(newline)
(display #\space)
;(newline)
(display (quote teee))
(newline)
(display (+ '3  3))
(newline)
(display (symbol? '3))
(newline)
(display (eqv? 'c 'C))
  #\
